### ISSUE TITLE
esriJSON feature arrays not captured by parse() in arcgis.js

### ISSUE THREAD

**Issue by abenrob** [Esri/terraformer#104]
Is this intentional?
When I point to an AGS JSON rest endpoint and try to parse to geoJSON, the object matches no cases and the geoJSON object remains empty.
If I limit to one feature (e.g. arcgis.features[0]) the conversion succeeds.

**Comment by jgravois** [comment]
hello from 2018!

in [`@esri/arcgis-to-geojson-utils`](https://github.com/Esri/arcgis-to-geojson-utils) we ultimately landed support for converting arrays of Esri JSON features into a GeoJSON FeatureCollection and auto-incrementing `id`s.

its also worth noting:
* [RFC 7946](https://tools.ietf.org/html/rfc7946#section-3.2) the `id` requirement was downgraded from a MUST to a SHOULD
* the Geoservices spec doesn't emit arrays of features with dissimilar geometries.

**Comment by hoogw** [comment]
@jgravois 

can you show me example, how to do it?

----------------------------------------------------------
in @esri/arcgis-to-geojson-utils we ultimately landed support for converting arrays of Esri JSON features into a GeoJSON FeatureCollection and auto-incrementing ids.

**Comment by jgravois** [comment]
@hoogw no need to respost the same question in three different places. i've answered you in https://github.com/Esri/arcgis-to-geojson-utils/issues/30#issuecomment-378681650
