### ISSUE TITLE
GeoJSON Coordinate Validation

### ISSUE THREAD

**Issue by wanderer** [Esri/Terraformer#111]
Hello, Thank you for writing this! Its great!
I needed to have good geoJSON coordinate validation so I ended up writing a [geoJSON Validation Lib](https://github.com/craveprogramminginc/GeoJSON-Validation). I validate before I feed my JSON into Terraformer. But it might make sense to integrate validation and do the checks on the creation of the primitives. I don't think it would be too hard to add my library into the mix. If this is a route you think would make sense for you, would there be any interest in a PR?

**Comment by jgravois** [comment]
closing, but always happy to revisit.
