### ISSUE TITLE
Tests for errors in Feature and FeatureCollection

### ISSUE THREAD

**Issue by patrickarlt** [Esri/terraformer#125]
There are no tests for error cases in `FeatureCollection` https://github.com/Esri/Terraformer/blob/master/src/terraformer.js#L1285 or `Feature` https://github.com/Esri/Terraformer/blob/master/src/terraformer.js#L1260

**Comment by jgravois** [comment]
https://github.com/Esri/terraformer/blob/f568330808ff73ce5d8377bb206c17506d2e8238/spec/terraformerSpec.js#L612-L619

https://github.com/Esri/terraformer/blob/f568330808ff73ce5d8377bb206c17506d2e8238/spec/terraformerSpec.js#L653-L659
