### ISSUE TITLE
Examples need some love 

### ISSUE THREAD

**Issue by alaframboise** [Esri/Terraformer#179]
1. https://github.com/Esri/Terraformer/tree/master/examples needs a \dist\ directory with all .min libraries in them.  
2. Examples all have incorrect reference calls.

e.g. Terraformer.Store...

https://github.com/Esri/Terraformer/blob/master/examples/counties/viewer.js

**Comment by jgravois** [comment]
> You could start by just using the CDN links on http://terraformer.io/install/ instead of bundling all the .min versions into the repo.

examples/browser now points at a CDN (unpkg.com) 9b25de07d16c179aecfa43d095959c154d145352
