### ISSUE TITLE
Where is the terraformer-arcgis-parser.min.js CDN?

### ISSUE THREAD

**Issue by alaframboise** [Esri/Terraformer#245]
The first exists but the second doesn't.

```html
<script src="http://cdn-geoweb.s3.amazonaws.com/terraformer/1.0.4/terraformer.min.js"></script>
<script src="http://cdn-geoweb.s3.amazonaws.com/terraformer/1.0.4/terraformer-arcgis-parser.min.js"></script>
```

**Comment by geospatialem** [comment]
Agreed. I spent **way** too much time trying to even find the _terraformer-arcgis-parser.min.js_ file in the repo. 

I ended up finding it in [an example](https://raw.githubusercontent.com/Esri/Terraformer/master/examples/lib/terraformer-arcgis-parser.js) after some searching. While a CDN is nice, I think this should be added into the repo at the very least.

**Comment by jgravois** [comment]
the parser source code can be found in [Esri/terraformer-arcgis-parser](Esri/terraformer-arcgis-parser)

@geospatialem what sort of breadcrumb would have been helpful to lead you there?  it'd be really easy to clarify the location of the source code in the main `README.md` here.

**Comment by geospatialem** [comment]
@jgravois I'm getting a 404 page error on my end, is **[this](https://github.com/Esri/terraformer-arcgis-parser)** the link you were trying to get to?

For clarity, I think changes are needed to both the `README.md` and [Terraformer Getting Started](http://terraformer.io/getting-started/#browser) page.

Below are some potential recommendations: 

## For the [README.md](https://github.com/Esri/Terraformer#getting-started):
### Getting Started (Browser):
```
//Terraformer Library (Required)
//Learn more: https://github.com/Esri/Terraformer
<script src="http://cdn-geoweb.s3.amazonaws.com/terraformer/1.0.4/terraformer.min.js"></script>

//Terraformer Packages (Optional)
//ArcGIS Parser: https://github.com/Esri/terraformer-arcgis-parser
//WKT Parser: <GitHub link here>
//GeoStore: <GitHub link here>
<script src="terraformer-arcgis-parser.min.js"></script> //Define ArcGIS Parser package
<script src="terraformer-wkt-parser.min.js"></script> //Define WKT Parser package
<script src="terraformer-geostore.min.js"></script> //Define GeoStore package
```

## For the [Getting Started Page](http://terraformer.io/getting-started/#browser):
Currently the packages are listed above the browser option, and lead to a new page. Instead it might be beneficial to list the options together. For example:

### Browser
To use the Terraformer library, you **must include** the core Terraformer library with a `<script>` tag. 

If you would like to utilize any of the Terraformer packages: [ArcGIS parser](http://terraformer.io/arcgis-parser/), [WKT parser](http://terraformer.io/wkt-parser/), or [GeoStore](http://terraformer.io/geostore/), you **must include** the library with a `<script>` tag **in addition to the Terraformer library**.
```
//Terraformer Library (Required)
//Learn more: https://github.com/Esri/Terraformer
<script src="http://cdn-geoweb.s3.amazonaws.com/terraformer/1.0.4/terraformer.min.js"></script>

//Terraformer Packages (Optional)
//ArcGIS Parser: https://github.com/Esri/terraformer-arcgis-parser
//WKT Parser: <GitHub link here>
//GeoStore: <GitHub link here>
<script src="terraformer-arcgis-parser.min.js"></script> //Define ArcGIS Parser package
<script src="terraformer-wkt-parser.min.js"></script> //Define WKT Parser package
<script src="terraformer-geostore.min.js"></script> //Define GeoStore package
```

**Comment by jgravois** [comment]
would you be game to submit a pull request with these great suggestions?  building the site locally is fairly straightforward if you have ruby installed.

1. cd into the Terraformer repository
2. run `npm install` to lay down its dependencies
3. run `grunt middleman:build` to write the compile the static site in a new `docs-build` folder
4. run the `index.html` in your browser (using your web server of choice to host over http)

if you can't be bothered, i'll try to get to it soon myself.

**Comment by geospatialem** [comment]
For sure, I'll try and give it a go this evening. Unfortunately I don't have access to many of those dependencies at work. I'll let you know if I hit any hiccups.

**Comment by jgravois** [comment]
awesome! i am happy to help you troubleshoot if you get stuck.

**Comment by jgravois** [comment]
to answer ALs question, the CDN link i found via http://terraformer.io/install/ is:
[http://cdn-geoweb.s3.amazonaws.com/terraformer**-arcgis-parser**/1.0.4/terraformer-arcgis-parser.min.js](http://cdn-geoweb.s3.amazonaws.com/terraformer-arcgis-parser/1.0.4/terraformer-arcgis-parser.min.js)
