### ISSUE TITLE
LineString isn't great circle?

### ISSUE THREAD

**Issue by stutteringp0et** [Esri/Terraformer#250]
I have a map that is 100% covered with polygons, attempting to detect intersects with a linestring, 

Plotting from 40,40 to -80,40 should arc up to near 60N before diving back to 40N (great circle route).  Screenshot of this line attached below.

Attempting to detect polygons which intersect the linestring, I discovered that the linestring follows the line of latitude instead of the great circle route.

I can only assume that this is intentional.  This leads to the question, other than creating a MultiLineString , is there a primitive that utilizes a great circle route?

**Comment by jgravois** [comment]
a late response is better than no response. 👴 

> is there a primitive that utilizes a great circle route?

there is not.  generating your own great circle route and representing it in GeoJSON as a densified LineString would definitely be appropriate.
