### ISSUE TITLE
convexHull not calculating quite right

### ISSUE THREAD

**Issue by rwwagner90** [Esri/Terraformer#256]
I have a set of markers on my map, and I need to find the convexHull to draw a band around the area they cover. I have been using your convexHull function, but it appears to add extra points, in addition to the ones I would expect, so instead of one open band, I get a line going through it. See this image:
![screen shot 2015-01-28 at 2 39 20 pm](https://cloud.githubusercontent.com/assets/2640861/5945361/cc213680-a6fb-11e4-94c4-7d3510b65847.png)

Here is my code, so you can try to figure out what is happening:
```js
var coordinates = [
  [
    -47.62477455655798,
    -138.4735187484631
  ],
  [
    36.469906927009305,
    -73.73470109960341
  ],
  [
    -23.90746108362472,
    -52.10371205150936
  ],
  [
    47.0974,
    -50.8941
  ],
  [
    77.9545,
    -41.897
  ],
  [
    -38.6932406573265,
    -34.70846004509569
  ],
  [
    42.82259127217611,
    -26.047937977387733
  ],
  [
    79.4735,
    -1.5927
  ],
  [
    -71.262,
    7.7012
  ],
  [
    6.0765,
    29.3012
  ],
  [
    45.25526220325095,
    51.47447829151248
  ],
  [
    -42.1944,
    53.5215
  ],
  [
    -8.545684388897097,
    59.253134784565034
  ],
  [
    46.14845552269597,
    139.88685681538294
  ]
];
var geoJsonPoints = new Terraformer.Primitive({
          type: 'MultiPoint',
          coordinates: coordinates
        });
var convexHullOfMarkers = geoJsonPoints.convexHull();
```
convexHullOfMarkers.coordinates yields:

```js
[
  [
    [
      79.4735,
      -1.5927
    ],
    [
      46.14845552269597,
      139.88685681538294
    ],
    [
      -42.1944,
      53.5215
    ],
    [
      -71.262,
      7.7012
    ],
    [
      -47.62477455655798,
      -138.4735187484631
    ],
    [
      77.9545,
      -41.897
    ],
    [
      79.4735,
      -1.5927
    ],
```
I would expect it to end here, as it has returned to the point it started on, but then it gives me an additional 2 points, and returns back to the start again. See below:
```js
    [
      45.25526220325095,
      51.47447829151248
    ],
    [
      46.14845552269597,
      139.88685681538294
    ],
    [
      79.4735,
      -1.5927
    ]
  ]
]
```
Where are these extra points coming from?

**Comment by rwwagner90** [comment]
I have switched to using another library for this, and it appears to yield the correct shape, without the extra points. https://github.com/brian3kb/graham_scan_js
![screen shot 2015-01-28 at 5 37 10 pm](https://cloud.githubusercontent.com/assets/2640861/5948621/52388b70-a714-11e4-8e32-b2a27cc8d0f1.png)

Perhaps you could amend your implementation to fit that one? I would love to just use Terraformer.

**Comment by JerrySievert** [comment]
thanks for the issue - it appears that an error may have creeped in when moving from jarvis-march - i'll research and see what we can do to get it resolved asap.

**Comment by rwwagner90** [comment]
Thank you. I'll use the alternate library, until this has been resolved.

**Comment by rwwagner90** [comment]
So this works again?

**Comment by JerrySievert** [comment]
yes, as of Jan 29, when the algorithm was revered to jarvish-march.
