### ISSUE TITLE
Proposal: drop support for primitives and geostore and make each parser standalone

### ISSUE THREAD

**Issue by jgravois** [Esri/terraformer#268]
at this point it might be a good idea to trim down the scope of Terraformer
#### proposal

we continue to maintain the repositories below, and refactor them to follow the pattern in [arcgis-to-geojson-utils](https://github.com/esri/arcgis-to-geojson-utils)
- https://github.com/esri/terraformer-wkt-parser
- https://github.com/esri/terraformer-arcgis-parser

we deprecate/retire:
- Primitives
- spatial operations
- https://github.com/Esri/terraformer-geostore

we gut the repo here so that it contains only the documentation site for the parsers
- https://github.com/Esri/Terraformer

what say you @JerrySievert @patrickarlt @ajturner anyone/everyone else?

i would **love** help, but i'm not the kind of guy to delegate my own proposals

**Comment by JerrySievert** [comment]
i know that the wkt parser and the arcgis parser are both in use.

i am also planning on pulling in the primitives and spatial operations into another platform using terraformer.  i feel that if we took those away, it would make terraformer unusable.

**Comment by JerrySievert** [comment]
i would also support moving terraformer to its own organization (ala koopjs), which would support the additional functionality without completely gutting the module.

**Comment by dmfenton** [comment]
I'm using the spatial operations in [Winnow](https://github.com/dmfenton/winnow). Very useful for me. It would be nice not to have to instantiate primitives to do the spatial operations so I'd support pulling those out. But I'm not sure how valuable Terraformer is without these things.

**Comment by jgravois** [comment]
> @JerrySievert i feel that if we took those away, it would make terraformer unusable.

since we assist with conversion to geojson, isn't it as easy as mixing and matching with Turf.js?

> @dmfenton I'm not sure how valuable Terraformer is without these things.

its my impression that the most heavily used parts of Terraformer have always been the conversion tools.  my only intention is to whittle down the surface area of the project to what gets the most use and something that would be more manageable for me to oversee personally (working under the assumption that otherwise it would be more or less unmaintained).  

i definitely don't want to make any changes that would make the project less useful so i'm happy to receive the feedback.

**Comment by JerrySievert** [comment]
i feel that if we moved it to its own organization, and opened up the membership a bit, we'd get a little more traction with maintenance.

**Comment by dmfenton** [comment]
> since we assist with conversion to geojson, isn't it as easy as mixing and matching with Turf.js?

No Turf, does not have the same spatial predicates `within, intersects, contains`. It has some similar functionality where you could probably make those predicates work. But it relies on JSTS, which is slower than Terraform in my testing.

**Comment by JerrySievert** [comment]
@dmfenton i'm glad to hear that terraformer is faster, we spent a lot of time trying to optimize

**Comment by patrickarlt** [comment]
I think the best thing to do would be to:

1. Move Terraformer to it's own org, a la Koop
2. Split up the main Terraformer Package into
   * terraformer-arcgis - the ArcGIS parser
   * terraformer-wkt - The WKT parser
   * terraformer-spatial - within, intersects, contains, bbox, convex hull, mercator/geographic conversion ect... pretty much everything in the `Terraformer.Tools` namespace plus `within`, `intersects` and `contains` convenience methods
3. Deprecate all `Terraformer.Primitive` stuff
4. Deprecate `Terraformer.GeoStore` stuff

**Comment by JerrySievert** [comment]
i'm ok with #1 and #2, let's discuss #3, and fine with #4.

when do we want to move it all into its own org?  i'm excited to get this project active again (and have a team that can help).

**Comment by patrickarlt** [comment]
Since #3 seems to be the only thing that merits discussion I'll give my stance on it.

From an API design standpoint turning JSON objects (GeoJSON) into JavaScript Objects (Terraformer Primitives) is a huge pain like @dmfenton mentioned. The only real benefit is some convenience when calling utility methods like `thing.within(otherThing)` as opposed to within(thing, otherThing).

The main cost of Primitives and why I spun the ArcGIS parser out into its own repo is that in browsers using Primitives was simply a lot of extra dependency I didn't use.

If anyone is really interested in keeping primitives I am game but I think the core promise of Terraformer should be to work with *GeoJSON* not its own base object types. So the new `terraformer-arcgis`, `terraformer-wkt` and `terraformer-spatial` should all work with GeoJSON and if we want we could make a `terraformer-primitive` that simply curries all their functionality into a nice object.

**Comment by JerrySievert** [comment]
I can tackle the wkt parser.  will look to see if it still makes sense to stick with jison or move to something else.

**Comment by mpayson** [comment]
eager to help on this one @jgravois , let me know when/where

**Comment by mpayson** [comment]
quick questions on approach:
1. how should we handle potentially shared functions, such as `coordinatesContainPoint` written in "[/spatial](https://github.com/Esri/terraformer/blob/master/terraformer.js#L502)" used in "[/arcgis](https://github.com/Esri/arcgis-to-geojson-utils/blob/master/index.js#L84)", is that just a dependency?
2. typescript?

**Comment by JerrySievert** [comment]
this is what I sent John: 
> Do you plan on moving any of the old code over from the esri org?  If so, I can start on modernizing the tooling and code of the wkt module.

> Is there specific tooling you’re planning on?

> And is there an overall architecture of how you’re thinking everything should fit together?

**Comment by jgravois** [comment]
@maxpayson

good question! my instinct is that it'd make the project the most approachable if each of the three new libraries are entirely standalone.

perhaps we can duplicate code initially and then publish a 'helper' dependency in the same org and add it to each **bundle**?

@jerrysievert I've never been much of a tooling nerd. I like a lot of what we're using in rest-js, but I don't have my heart set on anything in particular.

my initial feeling is:

* JS (not TypeScript)
* Jasmine for Node.js tests, Karma for browser tests (but happy to consider something else)
* make it a monorepo

> Do you plan on moving any of the old code over from the esri org?

**definitely**. my plan (as of this morning) is to move _this_ repo into the new org and make it the monorepo. if it we're me by myself I'd probably lean really heavily on the tooling in https://github.com/esri/arcgis-to-geojson-utils and port it as quickly as possible but if you want to explore something new for the wkt parser I'm a-okay with following your lead in the other two.

is all that still clear as mud?

if you can't already tell, any suggestions/recommendations/questions or demands will be warmly received.

**Comment by jgravois** [comment]
today i _finally_ got around to creating a monorepo and porting `@terraformer/arcgis`.

https://github.com/terraformer-js/terraformer

my plan now is to start tracking to do items in the new repo. once we add `wkt`, `spatial` (and `common`?), :nail_care: the JSDoc and ship `v2.0.0` i'll archive all the Esri repos.

**Comment by jgravois** [comment]
i sat on it awhile, but i finally got around to finishing the port and publishing new packages on [npm](https://www.npmjs.com/search?q=%40terraformer).

[@terraformer/spatial](https://www.npmjs.com/package/@terraformer/spatial)
[@terraformer/wkt](https://www.npmjs.com/package/@terraformer/wkt)
[@terraformer/arcgis](https://www.npmjs.com/package/@terraformer/arcgis)

```html
<script type='module'>
  import { calculateBounds } from 'https://unpkg.com/@terraformer/spatial?module';

  calculateBounds({
    type: "Point",
    coordinates: [ 45, 60 ]
  })

  // [45, 60, 45, 60]
  </script>
```
i got the motivation i needed when someone in the wild cut their own library size in half by swapping in what i'd already finished and shaking the tree. 🌲 

given that no one besides me has responded to issues or pull requests in any Terraformer repos in years, i still think that archiving them and directing folks to [terraformer-js/terraformer](https://github.com/terraformer-js/terraformer) is the right call.
