### ISSUE TITLE
point within polygon

### ISSUE THREAD

**Issue by HelderFSFerreira** [Esri/Terraformer#301]
I think there is a bug on command **point.within(polygon)**

I'm using nodeJS v6.10.0 and google maps to get the coordinates.

My code:
![image](https://cloud.githubusercontent.com/assets/18551619/25064347/6a65849c-21f0-11e7-91cb-3080b86ec0f1.png)

Log of polygon:
![image](https://cloud.githubusercontent.com/assets/18551619/25064298/80bf0304-21ef-11e7-92d7-55abecf49a43.png)

Log of polygon.coodinates:
![image](https://cloud.githubusercontent.com/assets/18551619/25064310/b065be18-21ef-11e7-9ce4-384ed9571e93.png)

Log of point:
![image](https://cloud.githubusercontent.com/assets/18551619/25064323/e9a26ae6-21ef-11e7-8663-09815a842bd3.png)

I'm sure that the point is within of that polygon, but response is:
![image](https://cloud.githubusercontent.com/assets/18551619/25064334/368a5d14-21f0-11e7-81ea-1fb741a537ae.png)

I already tested with the polygon and the point of the documentation and the result is true.

am i doing something wrong or it is a bug?

**Comment by jgravois** [comment]
> A LinearRing is closed LineString with 4 or more positions. The first and last positions are equivalent (they represent equivalent points). Though a LinearRing is not explicitly represented as a GeoJSON geometry type, it is referred to in the Polygon geometry type definition.  ([ref](http://geojson.org/geojson-spec.html#linestring))

that pedantic point aside, i wasn't able to reproduce your error even before making the correction above.

```js
var geoJsonPoint = {
  "type": "Point",
  "coordinates": [-8.81549, 41.69619833333333]
};

var geoJsonPolygon = {
  "type": "Polygon",
  "coordinates": [[
    [-8.873006254434586, 41.73479067256878],
    [-8.851982094347479, 41.64187614968995],
    [-8.70480492711067, 41.70279709543996],
    [-8.534291535615921, 42.13997851460122],
    [-8.873006254434586, 41.73479067256878]
  ]]
};

Terraformer.Tools.polygonContainsPoint(geoJsonPolygon.coordinates, geoJsonPoint.coordinates); 
// true

var pointPrimitive = new Terraformer.Primitive(geoJsonPoint);
var polygonPrimitive = new Terraformer.Primitive(geoJsonPolygon);

pointPrimitive.within(polygonPrimitive);
// true
```

**Comment by HelderFSFerreira** [comment]
@jgravois totaly my fault, sorry.

My polygon has the coordinates inside of ''. I didn’t notice that, completely my fault.

I removed the ' with ParceFloat method, i don't know if it was the best solution, but it works!

Thank you!

**Comment by jgravois** [comment]
no worries.  I didn't catch that looking at your screenshot either.
