### ISSUE TITLE
Module size

### ISSUE THREAD

**Issue by tristanhoy** [Esri/Terraformer#302]
playing-around.js: 500KB
.sass-cache: 1.6MB

These aren't referenced anywhere in your project, any chance you could remove them? This will speed up deployments, especially to AWS Lambda.

**Comment by jgravois** [comment]
'.sass-cache' was already in the `.npmignore`.

i added 'playing-around.js' too and published [`v1.0.8`](https://github.com/Esri/Terraformer/releases/tag/v1.0.8). enjoy the ~2MB leaner build.

**Comment by tristanhoy** [comment]
Thanks :)
