### ISSUE TITLE
when I npm install terraformer

### ISSUE THREAD

**Issue by yanghuan2016** [Esri/Terraformer#304]
npm ERR! code E404
npm ERR! 404 no such package available : @types/geojson
npm ERR! 404
npm ERR! 404  '@types/geojson' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'terraformer'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by jgravois** [comment]
i'm not able to reproduce the problem you've reported

![screenshot 2017-04-24 22 01 39](https://cloud.githubusercontent.com/assets/3011734/25369554/971b4436-2939-11e7-8280-03ef00ad03a1.png)

what npm version do you have installed?
what operating system?

my guess is that you'd encounter the same error when calling `npm install @types/geojson`. can you confirm?

if so, can you test the approach described [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10508#issuecomment-238521899) to see whether it resolves the error please?

**Comment by thosil** [comment]
I got the same problem but found the root cause.
We're using an internal npm registry (sinopia) and it seems it doesn't like the "@types/geoson".
Hopefully there's a workaround:
https://github.com/rlidwka/sinopia/issues/426#issuecomment-258415918
In our case, I put a .npmrc file on top of the project like this:
    @types:registry=https://registry.npmjs.org/
    registry=http://our.internal.npm.server

**Comment by priyavivek1** [comment]
Even i am facing same issue. 
@thosil : i added this to my .npmrc, but it didnt work

@types:registry=https://registry.npmjs.org
registry=http://registry.npmjs.org/


E:\>npm install terraformer
npm WARN engine terraformer@1.0.8: wanted: {"node":">=4.2.6"} (current: {"node":
"0.10.38","npm":"1.4.28"})
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'types/geojson' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'terraformer'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "terraformer"
npm ERR! cwd E:\
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! not ok code 0

**Comment by priyavivek1** [comment]
UPDATE: i got it working by updating npm version to latest 4.5.0

**Comment by jgravois** [comment]
@priyavivek1 did you need to make a change to the `.npmrc` _and_ update npm to resolve the problem or was it updating npm all on its own that resolved the problem?

**Comment by priyavivek1** [comment]
@jgravois : i just updated npm.

**Comment by priyavivek1** [comment]
UPDATE: i got this working with npm @2.11.2 and node 0.10.39 and making chnages to .npmrc as mentioned above.

**Comment by yanghuan2016** [comment]
Yes, I use sinopia too, after I change registry to offical registry, it went normal.
