### ISSUE TITLE
Delete test_approximation_tests branch

### ISSUE THREAD

**Issue by aheinz-fe** [Esri/terraformer#311]
I was unable to mirror this repository due to a large file in a five year old unmerged branch.
> remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
> 
> remote: error: File examples/polygons/geojson/us-counties.geojson is 161.90 MB; this exceeds GitHub Enterprise's file size limit of 100.00 MB

**Comment by jgravois** [comment]
done.

the work in that branch was superseded by #265 (which uses Jasmine's built-in matcher [`toBeCloseTo`](https://jasmine.github.io/api/3.0/matchers.html))
