### ISSUE TITLE
Intersects behavior with Polygon and Point

### ISSUE THREAD

**Issue by nheminger** [Esri/terraformer#314]
It appears Terraformer is saying that a point that is on a boundary vertex of a polygon does **not** intersect that polygon. Is that expected behavior? Reading some documentation on ST_intersects seems to indicate that such cases should be considered intersection.

This test case should illustrate the issue:
https://jsbin.com/rilalovexa/edit?html,output

**Comment by jgravois** [comment]
you missed the warning Terraformer logs to the console.

> Type Point to Polygon intersection is not supported by intersects

if you take a look at [the source](https://github.com/Esri/terraformer/blob/e123457a38768be27d6f159e09ed40a51f42f547/terraformer.js#L945-L968), Point/Polygon `intersects()` is just a glorified `contains()`. if both those checks return false, the method bombs out with the warning above.

https://github.com/Esri/terraformer/blob/e123457a38768be27d6f159e09ed40a51f42f547/terraformer.js#L952-L954

i wish i coiuld suggest something else for testing intersections like that in browser and node land, but tbh, i don't actually know. 🤷‍♂️

**Comment by jgravois** [comment]
happy to chat more about this if you have any other questions.
