### ISSUE TITLE
Typescript error when using package in Angular 7 application

### ISSUE THREAD

**Issue by josiahpeters** [Esri/terraformer#318]
I'm having an issue referencing the terraform library from my Angular application. Typescript is not happy with the typings file:

```
error TS2416: Property 'type' in type 'Primitive<T>' is not assignable to the same property in base type 'GeoJsonObject'.
  Type 'string' is not assignable to type '"Polygon" | "Point" | "MultiPoint" | "LineString" | "MultiLineString" | "MultiPolygon" | "GeometryCollection" | "Feature" | "FeatureCollection"'.
```

**Comment by jgravois** [comment]
without being able to see what you were trying to declare, i can only guess that it's user error.

```ts
import { Point } from "geojson";
import * as Terraformer from "terraformer";

// works
const normalPoint:Point = ({
  type: "Point",
  coordinates: [1,2]
});

// also works
var primitivePoint = new Terraformer.Primitive<GeoJSON.Point>({
  type: "Point",
  coordinates: [1,2]
});
```

**Comment by josiahpeters** [comment]
I'm going to try and create a smaller standalone chunk of code that causes this to fail. I'm pulling in this library as a dependency through `terraformer-arcgis-parser`.

Don't worry about spending too much energy on this issue. I have a fix for it. I will submit a PR if I can distill the problem down to something that isn't just a problem with my code or environment.

**Comment by jgravois** [comment]
if all you're doing is converting back and forth between ArcGIS JSON and GeoJSON, the standalone package below is another option.

https://github.com/esri/arcgis-to-geojson-utils

it also has [types](https://www.npmjs.com/package/@types/arcgis-to-geojson-utils) (thanks to @JeffJacobson).

_someday_ you'll be able to run the command below and get a standalone package, but the refactor is a work in progress ref: https://github.com/Esri/terraformer/issues/268#issuecomment-450239804.

```bash
$ npm install @terraformer/arcgis
```

> I will submit a PR if I can distill the problem down to something that isn't just a problem with my code or environment.

sounds good. you're also welcome to just reply again to this issue.
