### ISSUE TITLE
retire terraformer.io

### ISSUE THREAD

**Issue by jgravois** [Esri/terraformer#319]
the https://terraformer.io domain expires 2019.12.04.

if we can't release and spruce up the doc for [`v2`](https://terraformer-js.github.io/terraformer/) before then we should just figure out how to publish the documentation we already have to https://esri.github.io/terraformer instead.

**Comment by jgravois** [comment]
d-day has arrived.

<img width="567" alt="Screen Shot 2019-12-04 at 9 15 58 AM" src="https://user-images.githubusercontent.com/3011734/70164813-b4977c00-1676-11ea-88bf-2b64a3f68758.png">

**Comment by jgravois** [comment]
I don't work at Esri anymore and didn't want to keep spending $38 every year to renew the domain.

if anyone wants to send me the money, I think there's a little more time within the grace period for me to renew it.
https://www.paypal.me/johngravois

I'm also happy to transfer the domain to anyone from Esri.

**Comment by hoogw** [comment]
$38/year only keep the domain? What about the server hosting fee?  

What is the web site server IP?  Can I point a new domain terraformer.net or terroformer.org, to that IP?


 Can I host another copy of this web site content at my server.

      [https://transparentgov.net/cleargov1/](https://transparentgov.net/cleargov1/)

I also can host your web site via IPFS networks. 
     
See my IPFS networks sample: 
 [https://transparentgov.net/json2tree/ipfs/ipfsList.html](https://transparentgov.net/json2tree/ipfs/ipfsList.html)

**Comment by hoogw** [comment]
$38/year only keep the domain? What about the server hosting fee?

Can I host another copy of this web site on my hosting server?

And get another name, like terraformer.xxx

If $38/year cover both domain AND server hosting fee, I would like to pay you now, so you have another one year to think about next steps.

**Comment by hoogw** [comment]
You can transfer domain to google domain only $12/years, all my domain has been transfer to google domains, it is really easy to transfer, and google domain are super to others.

**Comment by jwasilgeo** [comment]
Until we get the docs site building again and figured out where to host again (most likely, I'm willing to bet through github pages?) we always have the **Internet Archive Wayback Machine**!
https://web.archive.org/web/20190604024130/http://terraformer.io/

**Comment by jgravois** [comment]
> What about the server hosting fee?

there are no hosting fees. we're using GitHub Pages.

> What is the web site server IP?

there is no server IP anymore, because the domain is inactive.

> Can I host another copy of this web site content at my server.

I'd certainly be okay with you hosting the current website somewhere else. iirc though, without some tweaks, the site won't load correctly unless its at the root of its domain though.

https://github.com/Esri/terraformer/tree/gh-pages

> You can transfer domain to google domain only $12/years

I'm fairly certain you can't transfer an expired domain. we'll have to renew in place. afterwards, I would be more than willing to transfer it, but only to someone from Esri or a Terraformer contributor.

**Comment by hoogw** [comment]
@jgravois 

I am working on host another copy and other options. 
I prefer to pay your $38 renew + 5 years google domain transfer fee. 
Can you give a try to ask for grace period, if possible. then transfer to google domain, see if works. 
If works, I can save $38, only pay you 5 years google transfer fee.

**Comment by hoogw** [comment]
@jwasilgeo 

Thanks for the archive link, great job.
Where currently the web page host on?  Now we only lose domain, but we still have all those web page available?

(https://github.com/Esri/terraformer/tree/gh-pages)

This is only source code, I get that, but where is this source code host before domain expair?

You suggest host on github, means, no domain name needed any more?
So no fee?

what the URL looks like if host on github?

**Comment by jgravois** [comment]
> where is this source code host before domain expired?

like I said before, we've been using [GitHub pages](https://pages.github.com) to host the site. a [CNAME](https://github.com/Esri/terraformer/blob/gh-pages/CNAME) file is how GitHub knows about our custom domain.

> I prefer to pay your $38 renew + 5 years google domain transfer fee.
> Can you give a try to ask for grace period

I'm happy to renew the domain where it already is if someone sends me the funds to do it, I don't have time to research how to transfer it to Google Domains any time soon.

> You suggest host on github, means, no domain name needed any more?

correct. I just republished the old site at https://terraformer-js.github.io

a copy of the code can be found here: https://github.com/terraformer-js/terraformer-js.github.io/

in the long run we have two problems.
1. the internet has a *lot* of dead links pointing at https://terraformer.io
2. the old ruby website is woefully out of date. last time I tried to build the raw source I just ended up with headaches. this means making fixes/improvements an incredible hassle.

**Comment by hoogw** [comment]
@jgravois



I am not from Esri nor a Terraformer contributor. 
Not valid to take over this domain. That is ok, understood. 

> I'm happy to renew the domain where it already is if someone sends me the funds to do it, I don't have time to research how to transfer it to Google Domains any time soon.

It is not too bad. I had done transfer all my domains to google.  But only old domain owner can do it. I can't do it for you unless I am old domain owner.  When transfer, google send authorization to old domain admin page, you need to go back old domain admin page to authorized this transfer. That is the only confusing part. Other than that, it is all easy. 

       
[https://terraformer-js.github.io](https://terraformer-js.github.io)

Works great! 

> the internet has a lot of dead links pointing at https://terraformer.io
the old ruby website is woefully out of date. last time I tried to build the raw source I just ended up with headaches. this means making fixes/improvements an incredible hassle.

    
For most of people, as long as some where we can look up the document is enough. 
No matter it is old domain name or new xxx.github.io, all works same. 
I personally feel [https://terraformer-js.github.io](https://terraformer-js.github.io) is good enough.

google search engine will re-direct all search result to this new URL in a few days. 
Then it does not make much sense to keep old domain https://terraformer.io, it will confuse the google search engine and people.

**Comment by akuckartz** [comment]
> I would be more than willing to transfer it, but only to someone from Esri or a Terraformer contributor.

When a cybersquatter can aquire the domain he, she or it will do so - and that very likely will neither be someone from ESRI nor a Terraformer contributor...

**Comment by jgravois** [comment]
> It is not too bad. I had done transfer all my domains to google.

domains.google.com says, "Transferring this domain to Google Domains will cost $60 plus tax."

**Comment by jgravois** [comment]
actually this is because Google Domains charges $12 for '.com' domains and $60 for '.io' domains.

https://support.google.com/domains/answer/6010092#tld

that means we should leave it where it is.

**Comment by hoogw** [comment]
[https://support.google.com/domains/answer/6010092#tld](url)

$60 for '.io' domains is the (transfer fee + first year fee)
5 year will be 60 * 5 = $300
I do not realize the .io is a lot expensive than .net. .org. .com ( I got those for $12/yr).
$60/yr is more expensive than your current $38/yr. Transfer to google does not make sense. 

looks like $38/year is the lowest available so far, 

terraformer.info is $12/year available now. But you don't want it to be other than .io. Understood.

[https://terraformer-js.github.io](url)

works great,  google search engine will re-direct all search result to this new domain in a few days.

**Comment by jgravois** [comment]
> works great, google search engine will re-direct all search result to this new domain in a few days.

what makes you think search results are going to pick up on the site I just created?

**Comment by hoogw** [comment]
I can pay you $38 for now to extend for 1 year, but for a long run. 
If you eventually will drop it move to [https://terraformer-js.github.io](url), you should move it now(you already moved). 

if you move it now, like you already did, Google search engine will re-direct to new one quickly.
No one will need old domain any more.  

> what makes you think search results are going to pick up on the site I just created?

From my own domain experience.  Search 'transparentgov'   my website rank as 2nd place now. 
When I first set up website, the rank is not even on page.  The rank get into first page in maybe  a few month.  Your website is much busier because it have reputation for more than 7 years, google will get the rank into top much quick than my.   More people click your new site, will quickly improve the google rank. So I think you use new site today,  in a few days(I think), worse case, in a few month (like my domain), new site will fully replace your old domain. Your old domain will NOT LONGER appear in google search result. (I drop my old domain, google remove my old dead link from search result quickly). 

Keep the new github domain, I and other people will click your new site, more click, google will rank it to top result more quickly. soon, the new domain will completely replace old one in google search results. That all from my own domain experience.

**Comment by jgravois** [comment]
okay, that makes _much_ more sense.

1. you send me the money
2. I renew the domain
3. I add a redirect https://terraformer.io > https://terraformer-js.github.io
4. after a short time, search results will start pointing users to the new page
5. next year, when the domain expires it won't be valuable to cybersquatters anymore

thanks for offering to cover the cost of the renewal and for sharing your own experience.

**Comment by hoogw** [comment]
What is your decision? 
You want to keep old [https://terraformer.io]()
I pay you $38 for now to extend 1 year,  the following 5 years I will most likely pay years by years.

If you decide to use github domain, then nothing need to pay. 

Both works for me.  
-----------------------------
I just saw your comment, 
Ok, I pay you $38 now, 1 second.

**Comment by hoogw** [comment]
You should receive $38 now. Next year renew, please remind me.

**Comment by hoogw** [comment]
>  I add a redirect https://terraformer.io > https://terraformer-js.github.io

No, you do not need to. 
Just keep use the old one, next year renew, text me or email me at [https://transparentgov.net/cleargov1/769/open-source-whats-new](url)

**Comment by jgravois** [comment]
https://terraformer.io has been renewed and a permanent redirect to the new site is in place.

this will be easier on me than renewing it manually next year. thanks again!

**Comment by hoogw** [comment]
> https://terraformer.io has been renewed and a permanent redirect has been set up. it should begin forwarding in a few hours.

this will be easier on me than renewing it manually next year. thanks again!

You welcome. I respect your choice. You do not want to keep  [https://terraformer.io](https://terraformer.io) for a long run, understood.

**Comment by jgravois** [comment]
@hoogw was right. it only took a couple days.

![Screen Shot 2019-12-16 at 3 48 32 PM](https://user-images.githubusercontent.com/3011734/70952611-9e48d300-201b-11ea-9b83-370f1ee538da.png)
