### ISSUE TITLE
Circle radius is incorrect

### ISSUE THREAD

**Issue by zakjan** [Esri/terraformer#321]
With increasing latitude from the equator, polygon generated by Terraformer.Circle uses smaller radius than it is in reality.

See this comparison with @turf/circle library of circles with 250km radius on latitudes 0, 10, 20, ...

![Screenshot 2019-05-31 at 14 47 10](https://user-images.githubusercontent.com/173585/58706664-ff2bf900-83b2-11e9-8852-c7e1296d6e4e.png)

Turf - grey, Terraformer - blue

Please excuse my layman's description, I just compared the two libraries and Turf's output seems more correct by visual inspection.

**Comment by jgravois** [comment]
that definitely looks like a bug to me.

if you're interested in putting together a PR, I adapted a JS implementation of [Vicenty's Formulae](https://en.wikipedia.org/wiki/Vincenty%27s_formulae) a couple years ago that you're welcome to steal.

https://github.com/Esri/geotrigger-editor/pull/225

**Comment by zakjan** [comment]
I have used another library meanwhile.

**Comment by jgravois** [comment]
published as `@terraformer/spatial@2.0.5`
