### ISSUE TITLE
Compilation Error on Primitive in Typescript

### ISSUE THREAD

**Issue by mikaLhote** [Esri/terraformer#322]
I have installed the npm package v 1.0.9. In typescript (v 3.2.4), there is a compilation error in terraformer.d.ts file l.37 => 

Property 'type' in type 'Primitive<T>' is not assignable to the same property in base type 'GeoJsonObject'.
  Type 'string' is not assignable to type '"Point" | "MultiPoint" | "LineString" | "MultiLineString" | "Polygon" | "MultiPolygon" | "GeometryCollection" | "Feature" | "FeatureCollection"'

 Thanks

**Comment by gavinr** [comment]
Hi @mikaLhote! Thanks for the post. Could you please post a more clear case (including code) that will cause that error to show?

**Comment by mikaLhote** [comment]
Hi @gavinr,

I had 15 vulnerabilities and two warnings. 
I have not registered these vulnerabilities!
Npm proposed to launch an audit to fix these vulnerabilities. 
After running the audit, I did not have any more vulnerabilities but some warnings...

After that the compilation error is gone !

Below a piece of my package.json file:

"dependencies": {
    "@angular/animations": "^7.2.13",
    "@angular/common": "^7.2.13",
    "@angular/compiler": "^7.2.13",
    "@angular/core": "^7.2.13",
    "@angular/forms": "^7.2.13",
    "@angular/http": "^7.2.13",
    "@angular/platform-browser": "^7.2.13",
    "@angular/platform-browser-dynamic": "^7.2.13",
    "@angular/platform-server": "^7.2.13",
    "@angular/router": "^7.2.13",
    "@ng-bootstrap/ng-bootstrap": "^4.0.1",
    "@types/leaflet": "^1.2.14",
    "angular-font-awesome": "^3.1.2",
    "angular-popper": "^2.0.0",
    "bootstrap": "4.1.3",
    "core-js": "^3.0.1",
    "d3-array": "^2.0.3",
    "d3-axis": "^1.0.12",
    "d3-scale": "^3.0.0",
    "d3-selection": "^1.4.0",
    "d3-shape": "^1.3.5",
    "d3-time-format": "^2.1.3",
    "font-awesome": "^4.7.0",
    "jquery": "^3.3.1",
    "leaflet": "^1.4.0",
    "leaflet-defaulticon-compatibility": "^0.1.1",
    "leaflet-draw": "^1.0.4",
    "leaflet-draw-toolbar": "^0.3.0-alpha.1",
    "leaflet-toolbar": "^0.4.0-alpha.1",
    "popper.js": "^1.14.5",
    "rxjs": "^6.4.0",
    "rxjs-compat": "^6.4.0",
    "terraformer": "^1.0.9",
    "typescript-string-operations": "^1.3.1",
    "zone.js": "^0.9.0"
},
 "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.8",
    "@angular/cli": "^7.3.8",
    "@angular/compiler-cli": "^7.2.13",
    "@angular/language-service": "^7.2.13",
    "@compodoc/compodoc": "^1.1.7",
    "@types/d3": "^5.7.1",
    "@types/jasmine": "^3.3.12",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^11.13.5",
    "codelyzer": "^5.0.0",
    "concurrently": "4.1.0",
    "jasmine-core": "^3.4.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "^5.4.2",
    "rxjs-tslint": "^0.1.7",
    "ts-node": "~7.0.0",
    "tslint": "^5.16.0",
    "typescript": "^3.2.4",
    "webpack": "^4.30.0"
  }

**Comment by mikaLhote** [comment]
i think the (all) vulnerabilities came from Angular...

**Comment by zakjan** [comment]
Hi, I'm evaluating switching from Rollup to Pika build tool, and I started receiving the same TS build error. All libraries are up-to-date.

This PR fixes it https://github.com/Esri/terraformer/pull/323
