### ISSUE TITLE
http://terraformer.io Web site is down !!! attention !!!

### ISSUE THREAD

**Issue by hoogw** [Esri/terraformer#328]
http://terraformer.io Web site is down !!! attention !!!

Web site is not working since a week ago.

Please fix the problem. 

Is there anyway, I can look up the document on this web site?

**Comment by rgwozdz** [comment]
https://github.com/Esri/terraformer/issues/319

**Comment by hoogw** [comment]
$38/year only keep the domain? What about the server hosting fee?  

What is the web site server IP?  Can I point a new domain terraformer.net or terroformer.org, to that IP?


 Can I host another copy of this web site content at my server.

      [https://transparentgov.net/cleargov1/](https://transparentgov.net/cleargov1/)

I also can host your web site via IPFS networks.

**Comment by jwasilgeo** [comment]
Thanks for reminding us about this issue.  Let's keep the conversation going in #319 and close this issue.

**Comment by hoogw** [comment]
Ok, agree, close
