### ISSUE TITLE
localstorage Can NOT used in web worker, Can you add kvStorage support ?

### ISSUE THREAD

**Issue by hoogw** [Esri/terraformer#334]
I need to use localStorage as store in web worker, 

BUT,  https://stackoverflow.com/questions/6179159/accessing-localstorage-from-a-webworker
localStorage and sessionStorage are both undefined in a webworker process.

As alternative kvStorage should be supported

**Comment by hoogw** [comment]
kvStorage are suspended,  never mind. Should you support indexedDB ?

**Comment by jgravois** [comment]
did you mean to open this issue in https://github.com/Esri/terraformer-geostore-localstorage?

none of the geostore code has been touched in years. if you need something different than what's already up on GitHub, you'd need to pursue it on your own.

**Comment by hoogw** [comment]
Yes, I will use localstorage.   If localstorage is not be able to hold huge data, then I will use the IndexedDB, I will try to make one on my own. closed.
