### ISSUE TITLE
create new version based on current HEAD of master branch

### ISSUE THREAD

**Issue by darcyparker** [Esri/terraformer#335]
https://github.com/Esri/terraformer/pull/326 updated @types/geojson, but a new version was not created/tagged here. So `npm install terraformer@latest` installs 1.0.9.

I would like to see a new version so I can get the latest @types/geojson.  Thanks.

**Comment by jgravois** [comment]
until a release is published, you should be able to use whatever version of types/geojson you want by just importing them first.

ref: https://github.com/Esri/terraformer-wkt-parser/issues/38#issuecomment-568137343

**Comment by darcyparker** [comment]
Thanks for that link. Esri/terraformer-wkt-parser#38 (comment)

I am still having difficult getting it to work and getting a slightly different error from `tsc`:

```
node_modules/terraformer/terraformer.d.ts(38,16): error TS2416: Property 'type' in type 'Primitive<T>' is not assignable to the same property in base type 'GeoJsonObject'.
Type 'string' is not assignable to type '"Point" | "MultiPoint" | "LineString" | "MultiLineString" | "Polygon" | "MultiPolygon" | "GeometryCollection" | "Feature" | "FeatureCollection"'.
```
> Note: I also added `@ts-ignore` when GeoJSON is not used...
> ```typescript 
> //@ts-ignore: Need to import GeoJSON https://github.com/Esri/terraformer-wkt-parser/issues/38
> import * as GeoJSON from 'geojson';
> import terraWkt from 'terraformer-wkt-parser';
> ```

It seems `tsc` is trying to use 'geojson' in `node_modules/@types/geojson terraformer` rather than the the one in `node_modules/terraformer/node_modules/@types/geojson`.... hence the errors.

I have worked around this by `npm install`ing a specific commit id from master... but would love to see a small point release published so it just works.

**Comment by jgravois** [comment]
@gavinr you think you could tackle publishing terraformer this week using my breadcrumbs in https://github.com/Esri/terraformer-wkt-parser/issues/45#issuecomment-567252985?

**Comment by gavinr** [comment]
@jgravois sure. this would be `v1.0.10`?

**Comment by jgravois** [comment]
absolutely. thanks!

**Comment by jgravois** [comment]
done. https://github.com/Esri/terraformer/releases/tag/v1.0.10

**Comment by darcyparker** [comment]
Thanks @jgravois  and @gavinr !
